

##########################################################3
## 查询配置
###########################################################
querys: 
  # - '当天9点25分分时涨跌幅大于等于2% 当天竞价金额大于500万  当天9点25分分时涨停取反 当天9点25分分时量比大于5  当天前一天涨停取反 主板 非st  '
  - '当天的前30天有>=1次dde大于1亿 主板  当天前一天涨跌幅小于4 当天大单净比 当天涨跌幅大于5'
  - '2023年7月5日竞价涨跌幅大于等于2%，2023年7月5日9点25分分时量比大于5，（(2023年7月5日 9:25-9:59分时区间最高价-开盘价)/2023年7月4日的收盘价）>0.04，2023年7月4日涨停取反，主板，非st，资金流入1亿以上，委比大于50%'
limits: ~ # ['002522', '600037', '300773', '838924', '300556', '300366'] # limits为空 即不限制自选股
cookie: ~ # cookie为空 即使用免费版
############################################################
## 日期配置
############################################################
start_date: '2023/7/2' # '年/月/日'
end_date: '2023/7/8' # '年/月/日' 或 '今天'
############################################################
## 代理配置 
############################################################
proxy_url: ~ # 如果不使用代理 proxy_url 填 ~
crawl_internal: 60 # 爬取时间间隔
ip_internal: 460 # ip切换时间间隔
############################################################
## Excel写入配置
############################################################
file_name: 'query2'